# Generated by Django 3.2.4 on 2021-06-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_rooms_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='time',
        ),
        migrations.AddField(
            model_name='reception',
            name='time_since',
            field=models.CharField(max_length=10, null=True, verbose_name='Time since'),
        ),
        migrations.AddField(
            model_name='reception',
            name='time_until',
            field=models.CharField(max_length=10, null=True, verbose_name='Time until'),
        ),
    ]
