# Generated by Django 3.2.4 on 2021-06-06 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Category')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Position of work',
                'verbose_name_plural': 'Positions of work',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Text')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Time creating')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Time changing')),
                ('is_published', models.BooleanField(default=True, verbose_name='Post')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workers.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Worker of PM',
                'verbose_name_plural': 'Workers of PM',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
