# Generated by Django 3.2 on 2021-05-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Workers', 'verbose_name_plural': 'Worker'},
        ),
        migrations.AlterField(
            model_name='workers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
