# Generated by Django 3.2 on 2021-06-01 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_auto_20210602_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workers',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workers',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
