# Generated by Django 3.2 on 2021-06-02 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20210602_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Position of work', 'verbose_name_plural': 'Workers of PM'},
        ),
        migrations.AlterModelOptions(
            name='workers',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Worker of PM', 'verbose_name_plural': 'Workers of PM'},
        ),
    ]
