# Generated by Django 3.2 on 2021-06-03 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_auto_20210603_0155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Position of work', 'verbose_name_plural': 'Positions of work'},
        ),
    ]
